/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eventstore;

import com.eventstore.dbclient.*;

import java.io.IOException;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.ExecutionException;

public class Reader {

  public static void main(String[] args)
      throws ExecutionException, InterruptedException, IOException {
    EventStoreDBClientSettings setts =
        EventStoreDBConnectionString.parseOrThrow("esdb://localhost:2113?tls=false");

    EventStoreDBClient client = EventStoreDBClient.create(setts);

    ReadStreamOptions readStreamOptions = ReadStreamOptions.get().fromStart().notResolveLinkTos();

    ReadResult readResult = client.readStream("accounts", readStreamOptions).get();

    List<ResolvedEvent> resolvedEvents = readResult.getEvents();

    for (ResolvedEvent resolvedEvent : resolvedEvents) {
      AccountCreated createdEvent =
          resolvedEvent.getOriginalEvent().getEventDataAs(AccountCreated.class);

      System.out.println("Read Event " + createdEvent);
    }
  }
}
