/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eventstore;

import com.eventstore.dbclient.*;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.concurrent.ExecutionException;

public class ReaderReactive {

  public static void main(String[] args) throws InterruptedException {
    EventStoreDBClientSettings setts =
        EventStoreDBConnectionString.parseOrThrow("esdb://localhost:2113?tls=false");

    EventStoreDBClient client = EventStoreDBClient.create(setts);

    client.subscribeToStream("accounts", new AccountCreateSubscriber());

    synchronized (ReaderReactive.class) {
      ReaderReactive.class.wait();
    }
  }

  private static class AccountCreateSubscriber extends SubscriptionListener {
    @Override
    public void onEvent(Subscription subscription, ResolvedEvent event) {
      try {
        onEventException(event);
      } catch (IOException e) {
        throw new UncheckedIOException(e);
      }
    }

    private void onEventException(ResolvedEvent event) throws IOException {
      AccountCreated accountCreated = event.getOriginalEvent().getEventDataAs(AccountCreated.class);
      System.out.println("Reactive " + accountCreated);
    }
  }
}
